### ISSUE TITLE
server disconnecter (code: 1006)

### ISSUE THREAD

**Issue by 4ducks** [jlesage/docker-mediainfo#1]
I run the container successfully.
i see the web interface but i get a "server disconnected (code: 1006)" when hovering the cursor over the X , near the logo.
tried to add code to the nginx.conf, as described in the instruction - but that did not help.
i am running the docker over Ubuntu 18.04

I
![Capture](https://user-images.githubusercontent.com/61635836/76689408-53505300-663e-11ea-8ded-19863179ab98.JPG)
s there something to do ?

**Comment by jlesage** [comment]
Did you try with to clear your browser cache?  Do you have the same issue with another browser?

**Comment by 4ducks** [comment]
Cleared the cache in Edge browser and still not seeing the menu.
Tried in Google Chrome and seeing

**Comment by 4ducks** [comment]
Microsoft Edge: cleared the cache and still not working.
Firefox and Chrome: working great !

Thanks.
