### ISSUE TITLE
Dark mode no longer works

### ISSUE THREAD

**Issue by planetrocky** [jlesage/docker-mediainfo#6]
### Current Behavior

There should be a preference setting for dark mode inside MediaInfoGui - it’s not there.

`DARK_MODE` environment variable does nothing. Always in light mode, and missing toolbar icons.

### Expected Behavior

Select dark mode from MediaInfo GUI or with ENV variable.

Toolbar icons missing.

![IMG_1892](https://github.com/user-attachments/assets/d96c944b-f4a8-4329-a70c-8677feead159)

### Environment

- OS: Linux
- OS version: linux/amd64 4.4.302+
- CPU: Intel Denverton
- Docker version: 20.10.23
- Device model: DS1819+
- Browser/OS: Safari iOS 17.6

### Container creation

Synology Container App

### Container log

```text
[app         ] QApplication: invalid style override 'Adwaita-Dark' passed, ignoring it.
[app         ] 	Available styles: Windows, Fusion
```

### Container inspect

```text
"ENV=/root/.docker_rc",
                "USER_ID=1038",
                "GROUP_ID=65536",
                "SUP_GROUP_IDS=",
                "UMASK=0022",
                "LANG=en_US.UTF-8",
                "TZ=Europe/London",
                "KEEP_APP_RUNNING=0",
                "APP_NICENESS=10",
                "INSTALL_PACKAGES=",
                "PACKAGES_MIRROR=",
                "CONTAINER_DEBUG=0",
                "DISPLAY_WIDTH=1366",
                "DISPLAY_HEIGHT=1024",
                "DARK_MODE=1",
                "SECURE_CONNECTION=0",
                "SECURE_CONNECTION_VNC_METHOD=SSL",
                "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60",
                "WEB_LISTENING_PORT=5800",
                "VNC_LISTENING_PORT=5900",
                "VNC_PASSWORD=",
                "ENABLE_CJK_FONT=0",
                "WEB_AUDIO=0",
                "WEB_AUTHENTICATION=0",
                "WEB_AUTHENTICATION_DEFAULT_USERNAME=",
                "WEB_AUTHENTICATION_DEFAULT_PASSWORD="
```

**Comment by jlesage** [comment]
Thanks for reporting. Fixed with the latest image!
